http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  task:
    host: localhost
    paths: '/tasks'
  assigner:
    host: localhost
    paths: '/assigner'
serviceEndpoints:
  edi:
    url: 'http://vvtsoft.ddns.net:5123/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - task
      - assigner
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: edi 
              changeOrigin: true
