http:
  port: 8180
admin:
  port: 9876
  host: localhost
apiEndpoints:
  profile-api:
    host: localhost
    path: '/profile'
  tasklist-api:
    host: localhost
    path: '/tasklist'
  task-api:
    host: localhost
    path: '/tasklist/:id/task'
serviceEndpoints:
  httpbin:
    url: 'http://5ca9ed1469c15c0014849041.mockapi.io'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - profile-api
      - tasklist-api
      - task-api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
