http:
  port: 8081
admin:
  port: 9876
  host: localhost
apiEndpoints:
  auth-api:
    host: localhost
    path: '/auth'
  all-tasks-api:
    host: localhost
    path: '/tasks'
  assigner-api:
    host: localhost
    path: '/assigner'
  
serviceEndpoints:
  authEnd:
    url: 'http://localhost:8089'
  tasksEnd:
    url: 'http://vvtsoft.ddns.net:5123'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  auth:
    apiEndpoints:
      - auth-api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: authEnd 
              changeOrigin: true
  tasks:
    apiEndpoints:
      - all-tasks-api
      - assigner-api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: tasksEnd 
              changeOrigin: true
