http:
  port: 8081
admin:
  port: 9876
  host: localhost
apiEndpoints:
  # MS viorel
  auth-api:
    host: localhost
    path: '/%7Brequest_tag:%22check_session_token%22,user_id:%22:ID%22,session_token:%:TOKEN%22%7D'
    prependPath:  false
    ignorePath:   true
  
  signup:
    host: localhost
    paths: '/%7Brequest_tag:%22signup%22,email:%22:EMAIL%22,password:%22:PAROLA%22,first_name:%22:NUME%22,last_name:%22:PRENUME%22%7D'
  login:
    host: localhost
    paths: '/%7Brequest_tag:%22login%22,email:%22:EMAIL%22,password:%22:PAROLA%22%7D'
  logut:
    host: localhost
    paths: '/%7Brequest_tag:%22logout%22,user_id:%22:ID%22,session_token:%:TOKEN%22%7D'
  check-session: 
    host: localhost
    paths: '/%7Brequest_tag:%22check_session_token%22,user_id:%22:ID%22,session_token:%:TOKEN%22%7D'
  # MS eduard
  all-tasks-api:
    host: localhost
    path: '/tasks'
  assigner-api:
    host: localhost
    path: '/assigner'

  # MS cristi
  get-pref:
    host: localhost
    paths: '/get-preferences/:id'
  edit-pref:
    host: localhost
    paths: '/edit-preferences/:accId/:time/:pref'
  delete-pref:
    host: localhost
    paths: '/delete-preferences/:userID'
  add-pref:
    host: localhost
    paths: '/add-preferences/:userID/:morning/:afternoon/:evening'

  get-profile:
    host: localhost
    paths: '/get-profile/:id'
  edit-profile:
    host: localhost
    paths: '/edit-profile/:accId/:time/:pref'
  delete-profile:
    host: localhost
    paths: '/delete-profile/:userID'
  add-profile:
    host: localhost
    paths: '/add-profile/:userID/:nume/:prenume/:email/:parola/:data_inregistrare'
  

  try:
    host: localhost
    paths: '/try-get/:idEmployee'  
  add:
    host: localhost 
    paths: '/add-underling/:idUnderling/:idSuperior/:position'
  change-sup:
    host: localhost 
    paths: '/change-superior/:idUnderling/:idSuperior'
  remove-und:
    host: localhost 
    paths: '/remove-underling/:idUnderling'
  view:
    host: localhost
    paths: '/viewUnderlings/:userID'

serviceEndpoints:
  # MS viorel
  authEnd:
    urls: 
      - 'http://18.220.57.109:8090'
      - 'http://18.220.57.109:8090'

  # MS eduard
  tasksEnd:
    urls: 
      - 'http://vvtsoft.ddns.net:5123'
      - 'http://vvtsoft.ddns.net:5123'

  # MS cristi
  preferences:
    url: 'http://104.199.20.255:8100/preferences/'
  profile:
    url: 'http://104.199.20.255:8100/profile/'
  employees:
    url: 'http://104.199.20.255:8099/employees/'
  
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  auth:
    apiEndpoints:
      - auth-api
      - signup
      - login
      - logut
      - check-session
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: authEnd 
              changeOrigin: true
  tasks:
    apiEndpoints:
      - all-tasks-api
      - assigner-api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: tasksEnd 
              changeOrigin: true

  # MS cristi
  preferences:
    apiEndpoints:
      - get-pref
      - edit-pref
      - delete-pref
      - add-pref
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: preferences 
              changeOrigin: true
  employees:
    apiEndpoints:
      - try
      - add
      - change-sup
      - remove-und
      - view
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: employees 
              changeOrigin: true
  profile:
    apiEndpoints:
      - get-profile
      - edit-profile
      - delete-profile
      - add-profile
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: profile 
              changeOrigin: true           

  