http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:

  get:
    host: localhost
    paths: '/get-preferences/:id'
  edit:
    host: localhost
    paths: '/edit-preferences/:accId/:time/:pref'
  delete:
    host: localhost
    paths: '/delete-preferences/:userID'
  try:
    host: localhost
    paths: '/try-get/:idEmployee'  
  add:
    host: localhost 
    paths: '/add-underling/:idUnderling/:idSuperior/:position'
  change-sup:
    host: localhost 
    paths: '/change-superior/:idUnderling/:idSuperior'
  remove-und:
    host: localhost 
    paths: '/remove-underling/:idUnderling'
  view:
    host: localhost
    paths: '/viewUnderlings/:userID'

serviceEndpoints:
  preferences:
    url: 'http://localhost:8099/preferences/'
  employees:
    url: 'http://localhost:8099/employees/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  preferences:
    apiEndpoints:
      - get
      - edit
      - delete
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: preferences 
              changeOrigin: true
  employees:
    apiEndpoints:
      - try
      - add
      - change-sup
      - remove-und
      - view
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: employees 
              changeOrigin: true

  